### ISSUE TITLE
Print issue in chrome

### ISSUE THREAD

**Issue by barbmc** [adchsm/Slidebars#175]
I have a print css that sets .sb-left to display:none. This works fine in firefox but in chrome if you print a page with the left slidebar open the slidebar still prints.

I also have this in my print css
#sb-site {min-height:0 !important;transform:none !important;box-shadow:none !important;}

Have you come across this before? Have any suggestions?

**Comment by barbmc** [comment]
I've managed to get rid of the slidebar content now but am still left with the space where it was.

**Comment by adchsm** [comment]
Hey,

I've not actually looked into print styles with Slidebars, I'll definitely make sure I look into it for a future version.

When you tried to print and the space still remained, was the Slidebar open or closed?

Thank,

Adam

**Comment by barbmc** [comment]
Open

--- Original Message ---

**Comment by barbmc** [comment]
My css works fine I'm firefox but not in chrome

--- Original Message ---

**Comment by adchsm** [comment]
Chrome might be printing the site at the transform: translate() amount too. Try a print style like this:

```css
@media print {
  .sb-slidebar {
    display: none;
  }

  #sb-site. .sb-site-container {
    -webkit-transform: translate( 0px );
    transform: translate( 0px );
    left: 0;
  }
}
```
