### ISSUE TITLE
Slidebars broke iOS & Chrome address bar auto-resize

### ISSUE THREAD

**Issue by robypez** [adchsm/Slidebars#251]
Hello everybody, I'm getting crazy because iOS and Chrome address bar doesn't auto resize while scrolling my website and now I discover that the fault is in Slidebars.

You can try also on the demo website: if you scroll on iOS the address bar is always visibile on top, try with another website and it disappear.

You can easy see the difference if you remove these rules

```
html, body {
    overflow: hidden;
}

canvas=container] {
    overflow-y: auto;
}
```

from the css. You remove the rules and the browser behavior is ok. By the way without that rules Slidebars are not ok. Any idea how to have a working Slidebars with the right browser behaviour?

**Comment by procmail** [comment]
Hi, any update on this issue please? Throughout the entire Sidebars site (https://www.adchsm.com/slidebars/), where the top menu is using Sidebars, the iOS Safari address bar never disappears when scrolling down.

**Comment by mnakalay** [comment]
I confirm and it makes sense since, with those rules, the body never scrolls so the bar will not disappear.

Still, it is a problem

**Comment by mnakalay** [comment]
you could try to add this script to your page as a temporary fix https://github.com/scottjehl/Hide-Address-Bar

**Comment by JoryHogeveen** [comment]
This also prevents the "refresh" action when swiping down in Chrome

**Comment by JoryHogeveen** [comment]
@adchsm 
Maybe an idea to set the canvas container on the body tag and make the script work with that instead of an inner element?

**Comment by JoryHogeveen** [comment]
Or another solution:

Change (https://github.com/adchsm/Slidebars/blob/master/dist/slidebars.css#L23):

``` css
html, body {
    width: 100%;
    height: 100%;
    overflow: hidden;
}
```

To:

``` css
html {
    overflow-y: auto;
}
html, body {
    width: 100%;
    overflow-x: hidden;
}
```

And change (https://github.com/adchsm/Slidebars/blob/master/dist/slidebars.css#L37):

``` css
[canvas=container] {
    width: 100%;
    height: 100%;
    overflow-y: auto;
    position: relative;
    background-color: white; /* Basic background color, overwrite this in your own css. */
    -webkit-overflow-scrolling: touch; /* Enables momentum scrolling on iOS devices, may be removed by setting to 'auto' in your own CSS. */
}
```

To:

``` css
[canvas=container] {
    width: 100%;
    position: relative;
    background-color: white; /* Basic background color, overwrite this in your own css. */
    -webkit-overflow-scrolling: touch; /* Enables momentum scrolling on iOS devices, may be removed by setting to 'auto' in your own CSS. */
}
```

Seems to work great here, will test some more.
