### ISSUE TITLE
new scroll bar position in v2

### ISSUE THREAD

**Issue by Brugman** [adchsm/Slidebars#255]
In v0.10 the browser scroll bar 'included' fixed elements while in v2 it doesn't. Why did this change? I much prefer old style. It keeps right floating elements in the nav bar aligned nicely with the next of the page, and if the nav bar is for example black the contrast between the black bar and white-grey Windows 7 scroll bar draws unwanted attention to the weird shape in the corner.

![slidebars-scrollbar-change](https://cloud.githubusercontent.com/assets/2203813/18748043/d5534526-80d0-11e6-8c15-1e9314bf4364.png)

I got the old style back in v2 with:

``` css
html { overflow-y: scroll; }
body, [canvas=container] { overflow: visible; }
```
